apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-simple
  namespace: open-liberty-demo
spec:
  replicas: 1
  # Note: replace "${Container_Registry_URL}" with your container registry URL
  applicationImage: ${Container_Registry_URL}/javaee-cafe-simple:1.0.0
  pullSecret: registry-secret
  expose: true
