apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: open-liberty-demo
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      paths:
        - /logs/messages*.log
      json.message_key: message
      json.keys_under_root: true
      json.add_error_key: true
    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}
